challenge:
  n_ch_per_epoch: 4
  docker_ulimit: 32768
  allowed_pip_pkg_dt: "2025-01-01T00:00:00Z"
  allowed_file_exts: [".py", ".json", ".yaml", ".yml", ".txt", ".pt"]
  bot_timeout: 30
  window_width: 1420
  window_height: 740
  n_checkboxes: 5
  cb_min_distance: 300
  cb_gen_max_factor: 20
  cb_size: 50
  cb_exclude_areas: [{ "x1": 500, "y1": 400, "x2": 950, "y2": 700 }]
